### ISSUE TITLE
QN Error thrown for sites+Index with randomTensor

### ISSUE THREAD

**Issue by ryanlevy** [ITensor/ITensor#170]
Hi Miles,

The static_assert ([here](https://github.com/ITensor/ITensor/blob/master/itensor/iqtensor_impl.h#L150)) in the IQTensor version of randomTensor is getting thrown for the following ITensor example:
```c++
auto sites = SpinHalf(N);
std::vector<Index> links(N+1);
//generate links
//...
auto W = randomTensor( sites(2),prime(sites(2)),links.at(1),links.at(2));
```
Note that replacing `auto` with `ITensor` doesn't change behavior. The easy but slightly annoying solution to this is
<pre>
<code>W = randomTensor( <b>(Index)</b> sites(2),<b>(Index)</b> prime(sites(2)),links(1),links(2));  </code>
</pre>
This is not particularly urgent but would be nice to not have to cast everywhere in the future

Thanks!

**Comment by emstoudenmire** [comment]
Hi Ryan,
Thanks for posting this issue; however, the reason for the error is actually that this is the incorrect usage of this function. For IQTensors, it's required that the first argument be a QN object saying what "QN flux" you'd like the returned IQTensor to have. (Otherwise it's not possible to generate a random IQTensor without this information.) 

Alternatively, there is also a version of randomTensor -> IQTensor that takes a collection of IQndexVal objects (IQIndices pegged to specific values like i1(3) or j(2)) and which returns a random IQTensor with random numbers in all blocks having the same QN flux as the one containing the element specific by the IQIndexVals.

More info on this page: http://itensor.org/docs.cgi?page=classes/iqtensor

Best regards,
Miles

**Comment by ryanlevy** [comment]
Hi Miles,

Sorry if my original error was unclear. I didn't want an `IQTensor` but a `ITensor` instead. In my mind, the compiler seems to be selecting the wrong templated function, as I wanted to return an `ITensor` where I don't care about what what QN sectors I'm in. If I'm still using this incorrectly please let me know!

**Comment by emstoudenmire** [comment]
Hi Ryan,
I see, ok thanks for clarifying. Yes this is a design issue with ITensor (sort of because of tricky aspects of C++ too). The issue is that I tried to make the site set classes, such as SpinHalf, work for both ITensors and IQTensors. Since IQIndices are convertible to regular Index objects I thought this could work. But it's caused a lot of hassle since C++ functions can only ever return one type, so that type has to be IQIndex if there's only one type of site set. 

I'm planning soon to go back to having two types of site sets: one for ITensors and one for IQTensors. So like SpinHalf and QSpinHalf. It's not ideal either but that's the best I can think of at the moment. In Julia (which we are planning to do a port of ITensor to) where functions can return different types depending on their arguments we may try to make things a little simpler when it comes to site sets.

Let me know if you have another suggestion. 

For now, you can either move your link indices to the front (then I think the function will deduce the rest of the indices to be Index type) or cast as you are doing. 

I'm going to close this as a bug, though, because it's more of a lack of an ideal design trade-off thing that we plan to improve, but is not currently a bug per se.

Best regards,
Miles

**Comment by ryanlevy** [comment]
Sounds good, thanks for clarifying. You're correct that the reorder is an easy fix to this too, which I like better than my own workaround. 

I just wasn't sure if there was some C++ cleverness to work around the problem but it looks like there's deeper things going on.

**Comment by ryanlevy** [comment]
For documentation, I found another example of the same sort of problem:
```c++
auto i = sites(1);
auto j = sites(2);
auto T = ITensor(i,j);
T.order(i, j);
```

This fails with a compilation error 
```
error: no matching function for call to 'getDotInds'
    getDotInds<IndexT>(++it,std::forward<Rest const&>(rest)…);
```

The temporary fix is of course `T.order((Index) i, (Index) j);`

**Comment by emstoudenmire** [comment]
Hi Ryan,
Thanks - it's helpful to know about this. We are actually working on a new ITensor version 3.0 that will definitely fix this issue. It will be released very soon, hopefully in a month's time. This new version will only have one kind of index (Index) and will no longer even have the IQIndex type. 

Best regards,
Miles
